<?php

/**
 * TokensTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TokensTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TokensTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tokens');
    }
}